config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :resources
  resources :structures
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "resources#index"
end

app/models/structure.rb
class Structure < ApplicationRecord
  has_many :recipes
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: %i[ show edit update destroy ]

  # GET /structures or /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1 or /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures or /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: "Structure was successfully created." }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1 or /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: "Structure was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1 or /structures/1.json
  def destroy
    @structure.destroy!

    respond_to do |format|
      format.html { redirect_to structures_path, notice: "Structure was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def structure_params
      params.expect(structure: [ :name ])
    end
end

app/views/structures/_form.html.erb
<%= form_with(model: structure) do |form| %>
  <% if structure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
        <% structure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/structures/_structure.html.erb
<div id="<%= dom_id structure %>">
  <p>
    <strong>Name:</strong>
    <%= structure.name %>
  </p>

</div>

app/views/structures/edit.html.erb
<% content_for :title, "Editing structure" %>

<h1>Editing structure</h1>

<%= render "form", structure: @structure %>

<br>

<div>
  <%= link_to "Show this structure", @structure %> |
  <%= link_to "Back to structures", structures_path %>
</div>

app/views/structures/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Structures" %>

<h1>Structures</h1>

<div id="structures">
  <% @structures.each do |structure| %>
    <%= render structure %>
    <p>
      <%= link_to "Show this structure", structure %>
    </p>
  <% end %>
</div>

<%= link_to "New structure", new_structure_path %>

app/views/structures/new.html.erb
<% content_for :title, "New structure" %>

<h1>New structure</h1>

<%= render "form", structure: @structure %>

<br>

<div>
  <%= link_to "Back to structures", structures_path %>
</div>

app/views/structures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @structure %>

<div>
  <%= link_to "Edit this structure", edit_structure_path(@structure) %> |
  <%= link_to "Back to structures", structures_path %>

  <%= button_to "Destroy this structure", @structure, method: :delete %>
</div>