config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :resources
  resources :structures
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "resources#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :structure

  has_many :input_resources
  has_many :output_resources

  has_many :inputs, through: :input_resources, source: :resource
  has_many :outputs, through: :output_resources, source: :resource

  validates :structure, presence: true
  validates :time, numericality: { greater_than: 0 }
  validates :faction, presence: true, inclusion: { in: %w[wardens colonials both], message: "%{value} must be 'wardens', 'colonials', or 'both'." }

  accepts_nested_attributes_for :input_resources
  accepts_nested_attributes_for :output_resources

  def time_formatted
    hours = (time / (1000 * 60 * 60)).to_s.rjust(2, '0')

    leftover_time = time % (1000 * 60 * 60)

    minutes = (leftover_time / (1000 * 60)).to_s.rjust(2, '0')

    leftover_time = leftover_time % (1000 * 60)

    seconds = (leftover_time / 1000).to_s.rjust(2, '0')

    milliseconds = (leftover_time % 1000).to_s.rjust(3, '0')

    output = "#{hours}:#{minutes}:#{seconds}"
    output += ".#{milliseconds}" unless time % 1000 == 0

    output
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_path, notice: "Recipe was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.fetch(:recipe, {})
    end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Inputs</h4>
  <div>
    <%= form.fields_for :recipe_inputs do |recipe_input_form| %>
      <%= recipe_input_form.text_field :input_id %>
    <% end %>
  </div>

  <h4>Outputs</h4>
  <div>
    <%= form.fields_for :recipe_outputs do |recipe_output_form| %>
      <%= recipe_output_form.text_field :output_id %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <%= recipe.output_resources.map(&:resource).map(&:name).join(" & ") %>
</div>

app/views/recipes/edit.html.erb
<% content_for :title, "Editing recipe" %>

<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Recipes" %>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<% content_for :title, "New recipe" %>

<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<h4>Inputs:</h4>
<ul>
<% @recipe.input_resources.each do |input_resource| %>
    <li>
      <%= render input_resource %>
    </li>
  <% end %>
</ul>

<h4>Outputs:</h4>
<ul>
<% @recipe.output_resources.each do |output_resource| %>
    <li>
      <%= render output_resource %>
    </li>
  <% end %>
</ul>

<p>
  <strong>Structure:</strong>
  <%= @recipe.structure.name %>
</p>

<p>
  <strong>Faction:</strong>
  <%= @recipe.faction.capitalize %>
</p>

<p>
  <strong>Time:</strong>
  <%= @recipe.time_formatted %>
</p>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>