config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :resources
  resources :structures
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "resources#index"
end

app/views/resources/_form.html.erb
<%= form_with(model: resource) do |form| %>
  <% if resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>">
  <p>
    <strong>Name:</strong>
    <%= resource.name %>
  </p>
  <p>
    <strong>Alias:</strong>
    <%= resource.alias || '-' %>
  </p>
</div>

app/views/resources/edit.html.erb
<% content_for :title, "Editing resource" %>

<h1>Editing resource</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Show this resource", @resource %> |
  <%= link_to "Back to resources", resources_path %>
</div>

app/views/resources/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Resources" %>

<h1>Resources</h1>

<div id="resources">
  <% @resources.each do |resource| %>
    <%= render resource %>
    <p>
      <%= link_to "Show this resource", resource %>
    </p>
  <% end %>
</div>

<%= link_to "New resource", new_resource_path %>

app/views/resources/new.html.erb
<% content_for :title, "New resource" %>

<h1>New resource</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Back to resources", resources_path %>
</div>

app/views/resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resource %>

<div>
  <%= link_to "Edit this resource", edit_resource_path(@resource) %> |
  <%= link_to "Back to resources", resources_path %>

  <%= button_to "Destroy this resource", @resource, method: :delete %>
</div>